### ISSUE TITLE
file_size utility is silly

### ISSUE THREAD

**Issue by jwakely** [olafurw/cznp-blog#1]
````
std::size_t file_size(const std::string& filename)
{
    std::ifstream in(filename, std::ios::in | std::ios::binary);

    std::string content;

    in.seekg(0, std::ios::end);
    content.resize(in.tellg());
    in.close();

    return content.size();
}
````

Why does this need to allocate a string of a potentially huge size, just to return that size?

Why can't you just convert `in.tellg()` to `size_t` and return that?

**Comment by olafurw** [comment]
"Why does this need to allocate a string of a potentially huge size, just to return that size?"

It doesn't.

"Why can't you just..."

I can.
